### ISSUE TITLE
More convenient appointment creation for upcoming Flex Times

### ISSUE THREAD

**Issue by ArnNag** [adityarathod/flexapp#35]
A feature that would facilitate the appointment-making process would be to show cards for the next two Flex Times (Wednesdays and Thursdays) whether or not the user has an appointment for those dates. If the user has an appointment for one of these dates, that card would show the appointment details as normal. If the user does not have an appointment for that date, the card would read "You do not have an appointment for [date]" and show a button that reads "Schedule one." When the button is clicked, the app would show an appointment creation dialog box with the date preselected.

**Comment by applecrazy** [comment]
This issue has been deferred until the `react-rewrite` is at feature parity with `master`.
